---
title: "SUDESA reporting"
author: "Data management SUDESA Team"
date: "8 février 2017"
output: pdf_document
---


#Summary of all fieldworkers for 7 last days

```{r, echo=FALSE, warning=FALSE, message=FALSE }

##Connexion on ODK
library(RMySQL)
library(dplyr)
library(ggplot2)
library(knitr)
library(stringr)
library(RPostgreSQL)
library(lubridate)
library(tidyr)

mydb = dbConnect(MySQL(), user='data', password='data', dbname='odk_prod', host='192.168.1.62')

##Connexion on openhds
mydb2 = dbConnect(MySQL(), user='data', password='data', dbname='openhds', host='192.168.1.62')

##Read data table at baseline
data.baseline <- dbReadTable(mydb, "BASELINE_CORE")

##Read data table for fielworker
data.fwd <- dbReadTable(mydb2, "fieldworker")
data.fwd.sub <- data.fwd[, c('extId', "firstName")]
names(data.fwd.sub)[1] <- "OPENHDS_FIELD_WORKER_ID"


data.baseline.sub <- data.baseline[, c("OPENHDS_LOCATION_ID", "START", 
                                       "INDIVIDUAL_INFO_INDIVIDUAL_ID", "OPENHDS_FIELD_WORKER_ID")]

data.baseline.sub$VISIT_DATE1 <- as.Date(str_sub(data.baseline.sub$START , 1, 10), format = '%Y-%m-%d')

##Merging 
data.baseline.sub <- merge(data.baseline.sub, data.fwd.sub, all.x = T)

##Read data table on location
data.location <- dbReadTable(mydb, "LOCATION_REGISTRATION_CORE")
data.location.sub <- data.location[, c("OPENHDS_LOCATION_ID", "QUARTER")]

##Merging
data.merging <- merge(data.baseline.sub, data.location.sub, all.x = F)

data.merging$VISIT_DATE2 <- rep(max(data.merging$VISIT_DATE1, na.rm = T), nrow(data.merging))
data.merging$Day <- data.merging$VISIT_DATE2 - data.merging$VISIT_DATE1

#Data for 7 lastdays
data.merging_D7 <- data.merging %>%
  filter(Day <= 8) %>%
    mutate(Day.name = wday(VISIT_DATE1, label = T, abbr = F))%>%
     filter(!duplicated(OPENHDS_LOCATION_ID)) %>%
      count(VISIT_DATE1, firstName)
        #count(firstName)


#Cut-off for the number households per FWR
cutoff1 <- 10
cutoff2 <- 15

```


```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10, fig.height=10}

#Figure: Total number of households visited (n) per FWR

fig1.1 <- ggplot(data.merging_D7, aes(x = firstName, y = n)) + 
  geom_bar(stat = 'identity', fill="lightblue") + xlab('Field worker name') +
  ylab('Total number of households visited (n)')+ geom_text(aes(y=n-1, label = n))+
  scale_y_continuous(breaks = c(1, 5, 10, 15, 20, 25))+
  geom_hline(yintercept = cutoff1, colour="red", linetype = "longdash") +
  annotate("text", x=1, y=cutoff1+1, label="Minimum", colour="red", size=3) +
  geom_hline(yintercept = cutoff2, colour="blue", linetype = "longdash") +
    annotate("text", x=1, y=cutoff2+1, label="Maximum", colour="blue", size=3)+
  theme(axis.text.x = element_text(angle=90))+
  facet_grid(VISIT_DATE1~.)

fig1.1 
```




\pagebreak


#Global statistics summary

```{r, echo=FALSE, warning=FALSE, message=FALSE }

##Connexion on postgis
mydb3 <- dbConnect(dbDriver("PostgreSQL"), dbname='sudesa', host='192.168.1.62', port='5432', user='postgres', password='test' )

data.build <- dbReadTable(mydb3, "polygones_02_02_2017")

##Select the quarters with information (remove abongo and adouma for the moment)
data.build.sub <- data.build %>%
  #filter(!is.na(quarter) & quarter!='NA' & quarter!='Adouma' & quarter!='Abongo') %>%
    filter(!is.na(quarter) & quarter!='NA') %>%
    select(one_of(c("id_menage", "visited", "inhabited", "quarter", "type_habit","type_hab_1", "name_habit")))

##Modifie type habitation
data.build.sub$type_habit_a <- NA
attach(data.build.sub)

#For Households
cond1 <- !is.na(id_menage) & (type_habit == '0'|type_habit == 'menage')
#cond1 <- (type_habit == '0'|type_habit == 'menage')
data.build.sub$type_habit_a[cond1] <- 'Household visited'

#For households with residents absent
cond2 <- (is.na(id_menage) & type_habit == '2') | (is.na(id_menage) & type_hab_1 == 'Absent')
data.build.sub$type_habit_a[cond2] <- 'Household (Absents)'

# #For Building under construction
# cond3 <- is.na(id_menage) & type_habit == '1' 
# data.build.sub$type_habit_a[cond3] <- 'Building under construction'

# #For Toillet
# cond4 <- is.na(id_menage) & type_habit == '3' 
# data.build.sub$type_habit_a[cond4] <- 'Toillet'

#For refusal
cond5 <- (is.na(id_menage) & type_habit == '15') | (is.na(id_menage) & type_hab_1 == 'refus') 
data.build.sub$type_habit_a[cond5] <- 'Refusal'

#For others
cond6 <- !cond1&!cond2&!cond5
data.build.sub$type_habit_a[cond6] <- 'No household'

detach(data.build.sub)

# ##Sub data for all buildings without households
# data.OtherBuild <- data.build.sub %>%
#   filter(type_habit_a != 'Households')
N_buil_v <- nrow(data.build.sub)

tab1.1 <- data.build.sub %>%
  filter(!is.na(type_habit_a)) %>%
   group_by(type_habit_a) %>%
    summarise(N = n(), Perc = round(100*N/nrow(data.build.sub), 1)) %>%
      mutate(N1 = paste(N, ' (',Perc,'%',')', sep ='')) %>%
        select(one_of(c('type_habit_a', 'N1'))) %>%
         spread(type_habit_a, N1) %>%
           bind_cols(Build.visit = data.frame(Buildings.visited = paste(N_buil_v, '(100%)')))
          
```

```{r fig.show=T, eval=FALSE, fig.height=5, message=FALSE, warning=FALSE, include=FALSE}

##Number of buildings per type
tab1 <- data.OtherBuild %>%
  filter(!is.na(type_habit_a)) %>%
   count(type_habit_a) 


fig1.1 <- ggplot(tab1, aes(x = type_habit_a, y = n)) + 
  geom_bar(stat = 'identity', fill="lightblue") + xlab('Type of buildings') +
  ylab('Total number (n)')+ geom_text(aes(y=n-10, label = n))+
  theme(axis.text.x = element_text(angle=-90))

fig1.1 

```

```{r, include=FALSE}
data.build.sub2 <- data.build %>%
  distinct(id, .keep_all = T)

##Modifie type habitation
data.build.sub2$type_habit_a <- NA
attach(data.build.sub2)

#For Households
cond1 <- !is.na(id_menage) & (type_habit == '0'|type_habit == 'menage')
#cond1 <- (type_habit == '0'|type_habit == 'menage')
data.build.sub2$type_habit_a[cond1] <- 'Households'

#For households with residents absent
cond2 <- (is.na(id_menage) & type_habit == '2') | (is.na(id_menage) & type_hab_1 == 'Absent')
data.build.sub2$type_habit_a[cond2] <- 'Households (Absents)'

#For refusal
cond5 <- (is.na(id_menage) & type_habit == '15') | (is.na(id_menage) & type_hab_1 == 'refus') 
data.build.sub2$type_habit_a[cond5] <- 'Refusal'

#For others
cond6 <- !cond1&!cond2&!cond5
data.build.sub2$type_habit_a[cond6] <- 'Others'

detach(data.build.sub2)

#Statistics
#Number of
tab2.1 <- data.build.sub2 %>%
  group_by(type_habit_a) %>%
    summarise(N =n() , Perc = round(100*N/nrow(data.build.sub2),1))

#Number of buildings
N_buil <- nrow(data.build.sub2)

#Number of buildings visited
Per_buil_v <- round(100*N_buil_v/N_buil, 1)

#Number estimated households
#We assume to have 6 persons in average per household. We know that the population size in
#Lambarene is 57,880

N_hous <- ceiling(57880/6)
Perc_hous <- round(100*N_hous/N_buil, 1)

##Data for age pyramid
data.baseline.sub1 <- data.baseline %>%
  select(one_of('OPENHDS_LOCATION_ID', 'INDIVIDUAL_INFO_DATE_OF_BIRTH', 'INDIVIDUAL_INFO_GENDER',
                'START')) %>%
        mutate(DateBirth = as.Date(str_sub(INDIVIDUAL_INFO_DATE_OF_BIRTH , 1, 10), format = '%Y-%m-%d'),
               DateVisit = as.Date(str_sub(START , 1, 10), format = '%Y-%m-%d'),
               Age = ceiling(time_length(interval(DateBirth, DateVisit), 'years')),
               AgeGr = cut(Age, breaks = seq(0, 120, 10))) %>%
                 filter(!is.na(AgeGr))

tab2.2 <- data.baseline.sub1 %>%
            count(INDIVIDUAL_INFO_GENDER, AgeGr)

##Data for statistics person per household
tab2.3 <- data.baseline.sub1 %>%
  count(OPENHDS_LOCATION_ID) %>%
    summarise(M1 = ceiling(mean(n)), M2 = quantile(n, 0.25), M3 = quantile(n, 0.75)) %>%
      mutate(M4 = paste(M1, ' (', M2, '-', M3, ')', sep = '')) 
names(tab2.3)[4] <- 'Average population size per household(Q1-Q3)'
       
tab2.4 <- data.baseline.sub1 %>%
    summarise(M1 = ceiling(median(Age)), M2 = quantile(Age, 0.25), M3 = quantile(Age, 0.75)) %>%
     mutate(M4 = paste(M1, ' (', M2, '-', M3, ')', sep = '')) 
names(tab2.4)[4] <- 'Age median(Q1-Q3), Yrs'

tab2.5 <- data.baseline.sub1 %>%
   count(INDIVIDUAL_INFO_GENDER) %>%
    spread(INDIVIDUAL_INFO_GENDER, n) %>%
      mutate(sex.ratio = paste(F, '/', M, sep = ''))
names(tab2.5)[3] <- 'Sex ratio(F/M)'

tab2.6 <- tab2.3[, 4] %>%
  bind_cols(as.data.frame(tab2.4[, 4]), as.data.frame(tab2.5[, 3]))

```


|Buildings total|Buildings visited|Household estimated|
|:-------------:|:---------------:|:-----------------:|
|`r N_buil` (100%)|`r N_buil_v` (`r Per_buil_v`%)|`r N_hous` (`r Perc_hous`%)|


```{r, echo=FALSE, warning=FALSE, message=FALSE}
#Characteristics of all buildings visited
names(tab1.1)[5] <- 'Buildings visited'
kable(tab1.1[, c(5, 2, 1, 4, 3)], align = 'c')
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#Demographics Characteristics of lambarene population
names(tab2.6)[2] <- 'Age median(Q1-Q3), Yrs'
kable(tab2.6, align = 'c')
```


```{r, fig.show=T, echo=FALSE, warning=FALSE, message=FALSE , fig.height= 6, fig.width= 8}
#Pyramides des ages
## Tracer la pyramide des ages
fig2.1 <- ggplot(tab2.2, 
                 aes(x = AgeGr, y = n, fill = INDIVIDUAL_INFO_GENDER)) +
  ylab('Count(n)') + xlab('Age groups (Yrs)')+ labs(fill = 'Sex')+
  geom_bar(data = subset(tab2.2, INDIVIDUAL_INFO_GENDER == "F"),
           stat = "identity") +
  geom_bar(data = subset(tab2.2, INDIVIDUAL_INFO_GENDER == "M"),
           stat = "identity",
           position = "identity",
           mapping = aes(y = -n)) +
  scale_y_continuous(breaks=seq(-500,500,100), labels=abs(seq(-500,500,100)))  +
  coord_flip()

fig2.1

```
